### ISSUE TITLE
IllegalAccessError on Jenkins v2.320 and up

### ISSUE THREAD

**Issue by xx1501xx** [jenkinsci/aws-beanstalk-publisher-plugin#59] opened 2021-12-01 13:31 UTC
### Version report

Jenkins and plugins versions report:

Jenkins v2.320+ and AWS Elastic Beanstalk Publisher v1.8.1

- What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

- Package code into zip file
- Push to AWS Elastic Beanstalk via plugin

### Results

Expected result:

- Successful deploy to AWS

Actual result:

- Jenkins job fails and the following exception is seen in the console log:

ERROR: Step ‘Deploy into AWS Elastic Beanstalk’ aborted due to exception: 
java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBS3Uploader
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBS3Uploader.uploadArchive(AWSEBS3Uploader.java:129)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdater.perform(AWSEBEnvironmentUpdater.java:66)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBElasticBeanstalkSetup.perform(AWSEBElasticBeanstalkSetup.java:181)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBSetup.perform(AWSEBSetup.java:22)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBPublisher.perform(AWSEBPublisher.java:73)

I believe this is caused by Jenkins v2.320 upgrade (See 'What's new in 2.320' on https://www.jenkins.io/changelog/):
- Upgrade the Guava library from 11.0.1 (released on January 9, 2012) to 31.0.1 (released on September 27, 2021).

**Comment by Hildebrand-Ritense** [comment] 2021-12-14 09:51
Jup, same here. Is David Tanner still maintaining this plugin? I must see the Guava tooling is quite a black box for me. So for now deploying the Beanstal .zip manually from the /tmp folder :)

**Comment by hilaweinstok** [comment] 2022-04-12 16:00
hi @Hildebrand-Ritense this command `git clone git@github.com:basil/aws-beanstalk-publisher-plugin.git
 ` doesnt work. it gives me this error:
fatal: Could not read from remote repository.
Please make sure you have the correct access rights

**Comment by basil** [comment] 2022-04-14 13:28
Fixed in https://github.com/jenkinsci/aws-beanstalk-publisher-plugin/pull/58. Released in [1.8.2](https://github.com/jenkinsci/aws-beanstalk-publisher-plugin/releases/tag/aws-beanstalk-publisher-plugin-1.8.2).

**Closed by basil** 2022-04-14 13:28 UTC
Labels: bug

**Comment by basil** [comment] 2022-04-29 00:48
Can someone please verify that the issue is resolved after upgrading to 1.8.2? Thanks!

**Comment by xx1501xx** [comment] 2022-04-29 20:44
It's working great for us.
--matt
